package runtime

import (
	"fmt"
	"sort"
	"strings"
)

// fastcgiConf is nginx's stock fastcgi.conf, which config templates include
// as {{fastcgi}}. Wharf writes its own copy so the generated config does not
// depend on where an install keeps its conf/. SERVER_PORT and HTTPS come from
// $wharf_port and $wharf_https, which each instance's main config defines:
// behind the front door they must be what the browser used, or Kirby writes
// the instance's own port into every link.
const fastcgiConf = `# Generated by Wharf — nginx's standard FastCGI parameters.
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_NAME        $server_name;
fastcgi_param  SERVER_PORT        $wharf_port;
fastcgi_param  HTTPS              $wharf_https if_not_empty;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
`

// mimes covers what a PHP site serves. Anything else is sent as
// application/octet-stream, which browsers download rather than display.
var mimes = map[string][]string{
	"text/html":                     {"html", "htm"},
	"text/css":                      {"css"},
	"text/plain":                    {"txt"},
	"text/xml":                      {"xml"},
	"text/csv":                      {"csv"},
	"text/markdown":                 {"md"},
	"text/javascript":               {"js", "mjs"},
	"application/json":              {"json", "map"},
	"application/manifest+json":     {"webmanifest"},
	"application/rss+xml":           {"rss"},
	"application/atom+xml":          {"atom"},
	"application/pdf":               {"pdf"},
	"application/zip":               {"zip"},
	"application/wasm":              {"wasm"},
	"image/gif":                     {"gif"},
	"image/jpeg":                    {"jpg", "jpeg"},
	"image/png":                     {"png"},
	"image/webp":                    {"webp"},
	"image/avif":                    {"avif"},
	"image/svg+xml":                 {"svg", "svgz"},
	"image/x-icon":                  {"ico"},
	"font/woff":                     {"woff"},
	"font/woff2":                    {"woff2"},
	"font/ttf":                      {"ttf"},
	"font/otf":                      {"otf"},
	"audio/mpeg":                    {"mp3"},
	"audio/ogg":                     {"ogg"},
	"video/mp4":                     {"mp4"},
	"video/webm":                    {"webm"},
	"application/vnd.ms-fontobject": {"eot"},
}

// mimeTypes renders the table in each webserver's own format: an nginx types
// block, or Apache's "type ext ext" lines.
func mimeTypes(server string) string {
	types := make([]string, 0, len(mimes))
	for t := range mimes {
		types = append(types, t)
	}
	sort.Strings(types)

	var sb strings.Builder
	sb.WriteString("# Generated by Wharf.\n")
	if server == "nginx" {
		sb.WriteString("types {\n")
		for _, t := range types {
			fmt.Fprintf(&sb, "  %s %s;\n", t, strings.Join(mimes[t], " "))
		}
		sb.WriteString("}\n")
		return sb.String()
	}
	for _, t := range types {
		fmt.Fprintf(&sb, "%s %s\n", t, strings.Join(mimes[t], " "))
	}
	return sb.String()
}
